[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
rustflags = ["--cfg", "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
# See here for config options: https://github.com/esp-rs/esp-idf-sys/blob/master/BUILD_OPTIONS.md
ESP_IDF_VERSION = "v5.2.1"

# These variables will ensure that the local partitions.csv is copied into the
# esp-idf build directory during compile time.
# The syntax is a bit funky, check
# https://github.com/esp-rs/esp-idf-sys#esp_idf_glob_xxx_base-and-esp_idf_glob_xxx_yyy
ESP_IDF_GLOB_PARTITION_BASE = { value = ".", relative = true }
ESP_IDF_GLOB_PARTITION_CSV = "/partitions.csv"
